export const MOCK_DESTINATIONS = [
  {
    id: "destination-1",
    name: "Resort Hotel",
    location: "PRT",
    hotel_type: "Resort Hotel",
    image: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5ce?auto=format&fit=crop&w=900&q=80",
    description: "A mock resort destination using the hotel type and country code from the booking data.",
  },
  {
    id: "destination-2",
    name: "City Hotel",
    location: "GBR",
    hotel_type: "City Hotel",
    image: "https://images.unsplash.com/photo-1518544866330-95a85b8f8f6f?auto=format&fit=crop&w=900&q=80",
    description: "A mock city destination using the hotel type and country code from the booking data.",
  },
  {
    id: "destination-3",
    name: "Resort Hotel",
    location: "FRA",
    hotel_type: "Resort Hotel",
    image: "https://images.unsplash.com/photo-1505881502353-a1986add3762?auto=format&fit=crop&w=900&q=80",
    description: "A mock resort destination ready to be replaced by live CSV-backed data.",
  },
  {
    id: "destination-4",
    name: "City Hotel",
    location: "ESP",
    hotel_type: "City Hotel",
    image: "https://images.unsplash.com/photo-1465311440653-ba9b1d9b0f5b?auto=format&fit=crop&w=900&q=80",
    description: "A mock city destination ready to be replaced by live CSV-backed data.",
  },
  {
    id: "destination-5",
    name: "Resort Hotel",
    location: "DEU",
    hotel_type: "Resort Hotel",
    image: "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?auto=format&fit=crop&w=900&q=80",
    description: "A mock resort destination with a stable image and destination detail link.",
  },
  {
    id: "destination-6",
    name: "City Hotel",
    location: "ITA",
    hotel_type: "City Hotel",
    image: "https://images.unsplash.com/photo-1500835556837-99ac94a94552?auto=format&fit=crop&w=900&q=80",
    description: "A mock city destination with a stable image and destination detail link.",
  },
];
