"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import Footer from "../footer/Footer";
import Header from "../header/Header";
import ImageUploader from "../../components/ImageUploader";
import OutfitImageCapture from "../../components/OutfitImageCapture";
import { useTravel } from "../TravelContext";
import { clampToSelectableDate, getMinSelectableDate, toDateString } from "../tripUtils";

const MAX_IMAGE_BYTES = 20 * 1024 * 1024;
const categories = ["Top", "Bottom", "Dress", "Shoes", "Outerwear", "Accessory"];
const adviceByWeather = { Sunny: "Choose light, breathable layers, sunscreen, a hat, and comfortable walking shoes.", Rainy: "Bring a rain jacket or umbrella, quick-dry clothes, and waterproof shoes.", Cloudy: "Comfortable layers and a light jacket are the safest choice." };
const getExpectation = (value) => { const raw = String(value || "").toLowerCase().replace(/_/g, " "); if (["shirt", "dress", "sandal"].some((item) => raw.includes(item))) return { conditions: ["Sunny"], phrase: "sunny, warm weather" }; if (["trouser", "pullover", "coat", "boot"].some((item) => raw.includes(item))) return { conditions: ["Cloudy", "Rainy"], phrase: "cool, cloudy, or rainy weather" }; return { conditions: ["Cloudy"], phrase: "this trip's weather" }; };
const formatDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "Select a date";
const generateDateRange = (startDate, endDate) => {
  if (!startDate || !endDate || endDate < startDate) return [];
  const dates = []; const current = new Date(`${startDate}T00:00:00`); const last = new Date(`${endDate}T00:00:00`);
  while (current <= last) { dates.push(toDateString(current)); current.setDate(current.getDate() + 1); }
  return dates;
};

export default function OutfitPlannerPage() {
  const { dateRange, currentActivities, outfits, setOutfits, savedItineraries } = useTravel();
  const [destinations, setDestinations] = useState([]); const [destination, setDestination] = useState(""); const [date, setDate] = useState(""); const [plannerDates, setPlannerDates] = useState([]); const [weather, setWeather] = useState(null); const [image, setImage] = useState(""); const [result, setResult] = useState(null); const [source, setSource] = useState("saved"); const [message, setMessage] = useState(""); const [loadingWeather, setLoadingWeather] = useState(false); const [loadingOutfit, setLoadingOutfit] = useState(false); const [captureSource, setCaptureSource] = useState(""); const [captureMode, setCaptureMode] = useState("");

  const readFromItinerary = () => {
    const latest = savedItineraries[0];
    const itineraryDates = latest?.itinerary?.map((day) => day.date || day.day).filter(Boolean) || [];
    const contextDates = generateDateRange(dateRange.startDate, dateRange.endDate);
    const dates = contextDates.length ? contextDates : itineraryDates;
    const savedDestination = currentActivities[0]?.destination || latest?.itinerary?.[0]?.destination || "";
    return { dates: dates.map(clampToSelectableDate), destination: savedDestination };
  };

  useEffect(() => {
    const saved = readFromItinerary();
    setPlannerDates(saved.dates); setDate(saved.dates[0] || clampToSelectableDate(getMinSelectableDate())); setDestination(saved.destination);
    let active = true;
    const load = async () => { let list; try { const response = await fetch("http://localhost:8000/destinations"); const data = await response.json(); if (!response.ok || !Array.isArray(data.destinations)) throw new Error(); list = data.destinations; } catch { const { MOCK_DESTINATIONS } = await import("../destinations/mockDestinations"); list = MOCK_DESTINATIONS; } if (!active) return; setDestinations(list); if (!saved.destination) setDestination(list[0]?.name || ""); };
    load();
    return () => { active = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const useSavedPlanner = () => { const saved = readFromItinerary(); setSource("saved"); setPlannerDates(saved.dates); setDate(saved.dates[0] || clampToSelectableDate(getMinSelectableDate())); setDestination(saved.destination || destination); setMessage(saved.dates.length ? "Saved planner dates and destination loaded." : "No saved itinerary dates were found yet. Add activities in the itinerary planner first."); };
  const getWeather = async () => { if (!destination || !date) { setMessage("Choose a place and date first."); return; } setLoadingWeather(true); setMessage(""); try { const match = destinations.find((item) => item.name === destination); const id = match?.id || destination.toLowerCase().replace(/\s+/g, "-"); const response = await fetch(`http://localhost:8000/destinations/${id}/forecast?date_str=${date}`); const data = await response.json(); if (!response.ok || !data.forecast) throw new Error(); setWeather({ condition: data.forecast.condition, temperature: data.forecast.average_temperature, rainfall: data.forecast.precipitation_sum_mm }); } catch { setWeather({ condition: "Cloudy", temperature: 27, rainfall: 0 }); setMessage("Live weather was unavailable, so a neutral forecast was used."); } finally { setLoadingWeather(false); } };
  const analyzeOutfit = async (dataUrl) => { if (dataUrl.length * 0.75 > MAX_IMAGE_BYTES) { setMessage("Please choose an image smaller than 20MB."); return; } setImage(dataUrl); setResult(null); setMessage(""); if (!destination || !weather) { setMessage("Choose a place, date, and predicted weather before uploading an outfit."); return; } setLoadingOutfit(true); try { const response = await fetch("http://localhost:8000/predict-outfit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image_base64: dataUrl }) }); const data = await response.json(); if (!response.ok || data.status === "error") throw new Error(data.message || "Outfit prediction failed."); const expectation = getExpectation(data.detected_category || data.weather_suitability); setResult({ ...data, category: "Top", matches: expectation.conditions.includes(weather.condition), outfitPhrase: expectation.phrase, advice: adviceByWeather[weather.condition] }); } catch (error) { setMessage(error.message || "Could not analyze outfit."); } finally { setLoadingOutfit(false); } };
  const acceptOutfit = () => { if (!result || !weather) return; const assignedDate = date || plannerDates[0] || clampToSelectableDate(getMinSelectableDate()); const dayIndex = Math.max(0, plannerDates.indexOf(assignedDate)); setOutfits((current) => [...current, { id: `${Date.now()}`, destination, date: assignedDate, weather: weather.condition, temperature: weather.temperature, rainfall: weather.rainfall, category: result.category, detectedCategory: result.detected_category, confidence: result.confidence_score, matches: result.matches, outfitPhrase: result.outfitPhrase, advice: result.advice, image, day: `Day ${dayIndex + 1}` }]); setResult(null); setImage(""); };
  const updateOutfit = (id, changes) => setOutfits((current) => current.map((outfit) => outfit.id === id ? { ...outfit, ...changes } : outfit));
  const deleteOutfit = (id) => setOutfits((current) => current.filter((outfit) => outfit.id !== id));
  const dayOptions = plannerDates.length ? plannerDates : [date || clampToSelectableDate(getMinSelectableDate())];

  return <main className="outfit-planner-shell min-h-screen bg-[#f5f7fa] text-slate-900"><Header /><div className="mx-auto max-w-7xl px-4 py-8 sm:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-slate-500">Wardrobe workspace</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-6xl">Attach outfit</h1></div><Link href="/final-planner" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Open final planner</Link></div>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 p-6"><p className="text-xs font-black uppercase tracking-wider text-slate-500">01 / Outfit source</p><h2 className="mt-2 text-2xl font-black">Where is this outfit for?</h2><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={useSavedPlanner} className={`rounded-lg px-3 py-2 text-sm font-bold ${source === "saved" ? "bg-slate-900 text-white" : "border border-slate-300"}`}>Use saved planner</button><button type="button" onClick={() => { setSource("new"); setPlannerDates([]); }} className={`rounded-lg px-3 py-2 text-sm font-bold ${source === "new" ? "bg-slate-900 text-white" : "border border-slate-300"}`}>New location</button></div><label className="mt-5 block text-sm font-bold">Location<select value={destination} onChange={(event) => { setDestination(event.target.value); setWeather(null); }} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-3">{destinations.map((item) => <option key={item.id || item.name}>{item.name}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Plan date<input type="date" min={getMinSelectableDate()} value={date} onChange={(event) => { setDate(event.target.value); setWeather(null); }} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-3" /></label><button type="button" onClick={getWeather} disabled={loadingWeather} className="mt-4 w-full rounded-lg bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-50">{loadingWeather ? "Checking weather..." : "Check predicted weather"}</button>{weather ? <div className="mt-4 border-t border-slate-200 pt-4"><p className="font-bold">{destination}: {weather.condition}</p><p className="mt-1 text-sm">{weather.temperature}°C average · {weather.rainfall} mm rain</p><p className="mt-2 text-sm text-slate-600">Garment matching is based on {weather.condition.toLowerCase()} conditions for {formatDate(date)}.</p></div> : null}</section>
      <section className="rounded-2xl border border-slate-200 p-6"><p className="text-xs font-black uppercase tracking-wider text-slate-500">02 / Capture</p><h2 className="mt-2 text-2xl font-black">Add one garment</h2><p className="mt-2 text-sm text-slate-600">JPG and image files up to 20MB are supported.</p><div className="mt-5 flex flex-wrap gap-3"><ImageUploader maxBytes={MAX_IMAGE_BYTES} onError={setMessage} onSelect={(dataUrl) => { setCaptureSource(dataUrl); setCaptureMode("image"); }} label="Upload outfit" /><button type="button" onClick={() => { setCaptureSource(""); setCaptureMode("camera"); }} className="rounded-full bg-slate-900 px-5 py-3 text-sm font-bold text-white">Use camera</button></div>{image ? <img src={image} alt="Garment preview" className="mt-5 h-48 w-full rounded-lg bg-slate-50 object-contain" /> : null}{loadingOutfit ? <p className="mt-4 text-sm font-semibold text-slate-600">Analyzing garment...</p> : null}{result ? <div className="mt-5 border-t border-slate-200 pt-4"><p className="font-bold">{result.matches ? "Weather match" : "Needs adjustment"}</p><p className="mt-2 text-sm text-slate-600">{destination} on {formatDate(date)} is expected to be {weather.condition.toLowerCase()}. This garment is suited for {result.outfitPhrase}.</p><p className="mt-2 text-sm text-slate-600">{result.advice}</p><label className="mt-4 block text-sm font-bold">Garment category<select value={result.category} onChange={(event) => setResult({ ...result, category: event.target.value })} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2">{categories.map((category) => <option key={category}>{category}</option>)}</select></label><div className="mt-4 flex gap-2"><button type="button" onClick={acceptOutfit} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Accept garment</button><button type="button" onClick={() => { setResult(null); setImage(""); }} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-bold">Reject</button></div></div> : null}{message ? <p className="mt-4 bg-rose-50 p-3 text-sm text-rose-700">{message}</p> : null}</section></div>
    <section className="mt-6 rounded-2xl border border-slate-200 p-6"><p className="text-xs font-black uppercase tracking-wider text-slate-500">03 / Accepted garments</p><h2 className="mt-2 text-2xl font-black">Garments by itinerary day</h2><p className="mt-2 text-sm text-slate-600">Multiple garments can be assigned to the same day.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{outfits.map((outfit) => <article key={outfit.id} className="group relative flex gap-4 border border-slate-200 p-4"><img src={outfit.image} alt={`${outfit.category} garment`} className="h-24 w-24 rounded-lg object-cover" /><div className="min-w-0"><h3 className="font-black">{outfit.category}</h3><p className="mt-1 text-xs text-slate-500">{outfit.destination} · {formatDate(outfit.date)} · {outfit.weather}</p><p className="mt-2 text-xs text-slate-600">{outfit.matches ? "Matches the selected weather" : "Review for the selected weather"}</p></div><div className="absolute right-3 top-3 hidden gap-2 group-hover:flex"><select aria-label={`Assign ${outfit.category} to a day`} value={outfit.date || dayOptions[0]} onChange={(event) => { const nextDate = event.target.value; updateOutfit(outfit.id, { date: nextDate, day: `Day ${Math.max(0, plannerDates.indexOf(nextDate)) + 1}` }); }} className="rounded border border-slate-300 bg-white px-2 py-1 text-xs font-bold">{dayOptions.map((day) => <option key={day} value={day}>Day {plannerDates.indexOf(day) + 1} · {formatDate(day)}</option>)}</select><button type="button" onClick={() => deleteOutfit(outfit.id)} className="rounded border border-rose-200 bg-white px-2 py-1 text-xs font-bold text-rose-700">Delete</button></div></article>)}{!outfits.length ? <p className="border border-dashed border-slate-300 p-8 text-center text-sm text-slate-600 md:col-span-2">Accepted garments will appear here.</p> : null}</div></section><div className="mt-8"><Footer /></div></div>{captureMode ? <OutfitImageCapture source={captureSource} mode={captureMode} onCancel={() => setCaptureMode("")} onSelect={(croppedImage) => { setCaptureMode(""); analyzeOutfit(croppedImage); }} /> : null}</main>;
}